# Generated by Django 5.1.7 on 2026-03-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_allergies_user_blood_type_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(blank=True, default=False, help_text='Set True when the user finishes or skips onboarding.'),
        ),
    ]
