services:
  - type: web
    name: PulseLink-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health/
    envVars:
      - key: DEBUG
        value: False
      - key: USE_REDIS
        value: True

