# Generated by Django 5.1.7 on 2026-03-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_order_paymongo_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='pharmacy_or_patient_57a892_idx',
            old_name='pharmacy_order_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='pharmacy_or_paymong_2623a7_idx',
            old_name='pharmacy_order_checkout_id_idx',
        ),
    ]
