# Generated by Django 6.0.3 on 2026-04-05 13:50

import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='pharmacyprescriptionupload',
            name='file',
            field=models.FileField(max_length=500, upload_to=pharmacy.models._rx_upload_path),
        ),
    ]
