# Generated by Django 5.1.7 on 2026-04-16 11:33

import cloudinary_storage.storage
import pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_raw_cloudinary_storage_for_prescription_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprescriptionupload',
            name='file',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=pharmacy.models._rx_upload_path),
        ),
    ]
