# Generated by Django 6.0.3 on 2026-03-20 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes, stored at upload time.', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'updated_at'], name='chat_conv_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['doctor', 'updated_at'], name='chat_conv_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='chat_msg_conv_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'sender'], name='chat_msg_unread_idx'),
        ),
    ]
