# Generated by Django 6.0.3 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_read_at_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='chat_files/'),
        ),
    ]
