# Generated by Django 5.1.7 on 2026-03-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_clinic_info_snapshot'),
        ('appointments', '0007_appointment_booked_for'),
    ]

    operations = [
    ]
