# Generated by Django 6.0.3 on 2026-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_cancellation_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
