# Generated by Django 5.1.7 on 2026-04-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_booked_for_email'),
        ('appointments', '0010_review_doctor_reply'),
    ]

    operations = [
    ]
