# Generated by Django 5.1.7 on 2026-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_booked_for_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_contact',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booked_for_relationship',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='family_member',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_for_name',
            field=models.CharField(blank=True, help_text='Full name of the person being seen. Empty = booking for self (logged-in user).', max_length=200, null=True),
        ),
    ]
