# Generated by Django 5.1.7 on 2026-04-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_appointment_booked_for_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_for_name',
            field=models.CharField(blank=True, default='', help_text='Cached full name from patient_profile. Empty = booking for self.', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('home_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_owner', models.ForeignKey(help_text='The logged-in user who created this profile', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_profile',
            field=models.ForeignKey(blank=True, help_text='Patient profile used for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.patientprofile'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['account_owner', '-created_at'], name='profile_owner_created_idx'),
        ),
    ]
