# Generated by Django 6.0.3 on 2026-04-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_allow_null_date_of_birth"),
        ("records", "0004_prescription_pdf_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("follow_up_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("ignored", "Ignored"), ("booked", "Booked")], default="pending", max_length=10)),
                ("ignored_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="follow_up_invitations", to="appointments.appointment")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="follow_up_invitations", to=settings.AUTH_USER_MODEL)),
                ("prescription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="follow_up_invitations", to="records.prescription")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="followupinvitation",
            index=models.Index(fields=["patient", "status", "-created_at"], name="followup_patient_status_idx"),
        ),
        migrations.AddIndex(
            model_name="followupinvitation",
            index=models.Index(fields=["appointment", "-created_at"], name="followup_appointment_idx"),
        ),
    ]
