# Generated by Django 5.1.7 on 2026-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_medicalcertificate_appointment_consulttranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
