# Generated by Django 6.0.3 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_prescription_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lab_results/'),
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='prescriptions/'),
        ),
    ]
