# Generated by Django 5.1.7 on 2026-03-20 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_expand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctors_doc_special_6fb0de_idx',
            old_name='doctor_specialty_city_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctors_doc_is_veri_20e5ad_idx',
            old_name='doctor_verified_invite_idx',
        ),
        migrations.AlterField(
            model_name='doctorhmo',
            name='name',
            field=models.CharField(choices=[('Maxicare', 'Maxicare'), ('Medicard', 'Medicard'), ('PhilCare', 'PhilCare'), ('Intellicare', 'Intellicare'), ('Caritas Health Shield', 'Caritas Health Shield'), ('Pacific Cross', 'Pacific Cross'), ('Insular Health Care', 'Insular Health Care'), ('Avega', 'Avega'), ('EastWest Healthcare', 'EastWest Healthcare'), ('Other', 'Other')], help_text='HMO provider accepted by this doctor.', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='About / professional summary shown on detail page.'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Metro Manila', 'Metro Manila'), ('Quezon City', 'Quezon City'), ('Makati', 'Makati'), ('Taguig', 'Taguig'), ('Pasig', 'Pasig'), ('Mandaluyong', 'Mandaluyong'), ('Cebu City', 'Cebu City'), ('Davao City', 'Davao City'), ('Iloilo City', 'Iloilo City'), ('Bacolod', 'Bacolod'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Zamboanga City', 'Zamboanga City'), ('Baguio', 'Baguio'), ('Other', 'Other')], db_index=True, help_text='City used for location-based filtering.', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='invite_accepted',
            field=models.BooleanField(default=False, help_text='Set True when doctor completes activation (sets password via invite link).'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_on_demand',
            field=models.BooleanField(default=False, help_text='Enables "Talk within 15 min" badge. Requires last_active_at within 10 min.'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin sets True after manual PRC license verification. Required for public listing.'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Updated by heartbeat ping from doctor app. Used for Available Now logic.', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='prc_license',
            field=models.CharField(help_text='7-digit PRC license number. Admin verifies before setting is_verified=True.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='PRC license must be exactly 7 digits.', regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Headshot shown on patient-facing cards. Builds trust (NowServing pattern).', null=True, upload_to='doctor_photos/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Pediatrics', 'Pediatrics'), ('OB-GYN', 'OB-GYN'), ('Dermatology', 'Dermatology'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('ENT', 'ENT (Ear, Nose & Throat)'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Urology', 'Urology'), ('Nephrology', 'Nephrology'), ('Oncology', 'Oncology'), ('Rheumatology', 'Rheumatology'), ('Surgery', 'Surgery'), ('Dentistry', 'Dentistry'), ('Other', 'Other')], db_index=True, help_text='Primary specialty shown prominently on the profile card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='sub_specialties',
            field=models.JSONField(blank=True, default=list, help_text='List of sub-specialty strings, e.g. ["Neonatology","Adolescent Medicine"].'),
        ),
        migrations.AlterField(
            model_name='doctorservice',
            name='name',
            field=models.CharField(choices=[('Medical Certificate', 'Medical Certificate'), ('Follow-up Consult', 'Follow-up Consult'), ('Prescription Renewal', 'Prescription Renewal'), ('Lab Result Interpretation', 'Lab Result Interpretation'), ('Sick Leave Certificate', 'Sick Leave Certificate'), ('Referral Letter', 'Referral Letter'), ('Annual Physical Exam', 'Annual Physical Exam'), ('Teleconsult', 'Teleconsult'), ('Home Visit', 'Home Visit'), ('Other', 'Other')], help_text='Service type offered by this doctor.', max_length=100),
        ),
    ]
