# Generated by Django 5.1.7 on 2026-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorprofile_weekly_schedule_doctoravailableslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthmo',
            name='coverage_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Admin-set coverage % applied to consultation fee'),
        ),
        migrations.AlterField(
            model_name='patienthmo',
            name='provider',
            field=models.CharField(help_text='e.g. Maxicare, Medicard', max_length=100),
        ),
    ]
