# Generated by Django 5.1.7 on 2026-03-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_patienthmo_coverage_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Set True when the doctor finishes the onboarding wizard.'),
        ),
    ]
