# Generated by Django 6.0.3 on 2026-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctorprofile_clinic_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Headshot shown on patient-facing cards. Builds trust (NowServing pattern).', max_length=500, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AlterField(
            model_name='patienthmo',
            name='card_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hmo_cards/'),
        ),
    ]
