# Generated by Django 6.0.3 on 2026-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_remove_city_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='E-signature image (PNG with transparent background) embedded in prescription PDFs.', max_length=500, null=True, upload_to='doctor_signatures/'),
        ),
    ]
