# Generated by Django 5.1.7 on 2026-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_add_signature_to_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='face_front',
            field=models.ImageField(blank=True, help_text='Front-facing liveness photo.', max_length=500, null=True, upload_to='face_verification/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='face_left',
            field=models.ImageField(blank=True, help_text='Left-side liveness photo.', max_length=500, null=True, upload_to='face_verification/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='face_right',
            field=models.ImageField(blank=True, help_text='Right-side liveness photo.', max_length=500, null=True, upload_to='face_verification/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_face_verified',
            field=models.BooleanField(default=False, help_text='Set True after all three face photos are captured and blink detected.'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='prc_card_image',
            field=models.ImageField(blank=True, help_text="Clear front photo of the doctor's PRC license card.", max_length=500, null=True, upload_to='prc_cards/'),
        ),
    ]
