# Generated by Django 5.1.7 on 2026-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_doctorprofile_face_verification_status_and_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='face_verification_error',
            field=models.TextField(blank=True, default='', help_text='Last face verification error, if any.'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='face_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('manual_review', 'Manual Review'), ('admin_override', 'Admin Override')], default='pending', help_text='Auto status for face verification; admin can override if needed.', max_length=20),
        ),
    ]
