# Generated by Django 5.1.7 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_remove_face_left_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='face_front',
            field=models.ImageField(blank=True, help_text='Liveness reference photo from AWS Rekognition.', max_length=500, null=True, upload_to='face_verification/'),
        ),
    ]
